services:
  immich:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - DB_HOSTNAME=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE_NAME=immich
      - REDIS_HOSTNAME=redis
    volumes:
      - ./data/upload:/data
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - database
      - redis

  machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: immich-machine-learning
    restart: unless-stopped
    volumes:
      - ./data/model-cache:/cache

  redis:
    image: docker.io/valkey/valkey:8
    container_name: immich-redis
    restart: unless-stopped

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich-database
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS=--data-checksums
    volumes:
      # Keep the database on an SSD
      - ./data/postgres:/var/lib/postgresql/data
    shm_size: 128mb
