services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    # Lets Caddy raise network buffers for HTTP/3
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      # HTTP/3 (QUIC)
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/data:/data
      - ./data/config:/config
    networks:
      - __NETWORK__

networks:
  __NETWORK__:
    external: true
