// @ts-check
import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import sitemap from '@astrojs/sitemap';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

/** Removes pages marked `noindex` (stubs, legal pages) from the sitemap generated by @astrojs/sitemap. */
const sitemapNoindex = () => ({
  name: 'sitemap-noindex',
  hooks: {
    'astro:build:done': ({ dir, pages, logger }) => {
      const root = fileURLToPath(dir);
      const noindex = new Set(
        pages
          .map((p) => p.pathname)
          .filter((p) => {
            const file = `${root}${p}${p === '' || p.endsWith('/') ? 'index.html' : '/index.html'}`;
            return fs.existsSync(file) && fs.readFileSync(file, 'utf8').includes('<meta name="robots" content="noindex"');
          })
          .map((p) => `https://yourhomelab.guide/${p}`),
      );
      for (const f of fs.readdirSync(root).filter((f) => /^sitemap-\d+\.xml$/.test(f))) {
        const xml = fs.readFileSync(root + f, 'utf8');
        const out = xml.replace(/<url>.*?<\/url>/g, (u) => (noindex.has(/<loc>(.*?)<\/loc>/.exec(u)?.[1]) ? '' : u));
        fs.writeFileSync(root + f, out);
      }
      logger.info(`${noindex.size} noindex pages removed from the sitemap`);
    },
  },
});

export default defineConfig({
  site: 'https://yourhomelab.guide',
  trailingSlash: 'always',
  // "/" has no page of its own; on the live server public/.htaccess sends a 301 before this is reached
  redirects: { '/': '/de/' },
  build: { format: 'directory', inlineStylesheets: 'auto' },
  compressHTML: true,
  prefetch: { prefetchAll: true, defaultStrategy: 'hover' },
  markdown: { syntaxHighlight: false },
  integrations: [
    mdx(),
    sitemap({ filter: (page) => !page.includes('/404') && page !== 'https://yourhomelab.guide/' }),
    sitemapNoindex(),
  ],
  devToolbar: { enabled: false },
  // Never inline scripts, so the CSP can use script-src 'self' without 'unsafe-inline'
  vite: { build: { assetsInlineLimit: 0 } },
});
