/**
 * Stack builder: turns the picked services plus "Mein Setup" into the files of the download
 * (compose.yaml, .env with fresh secrets, extra files, PROXY.txt, setup.sh, README.md).
 * Pure functions, used in the browser.
 */
import { appDataDir, placeholders, type Setup } from '../../config/site';
import { PH_RE } from '../highlight';

export interface StackService {
  id: string;
  name: string;
  /** Reverse proxy stack (category `proxy`): started first */
  isProxy: boolean;
  compose: string;
  env: string;
  proxy: string | null;
  proxyKind: 'caddy' | 'npm' | null;
  /** Needs the external proxy network */
  net: boolean;
  /** Central data folder has to be created */
  centralData: boolean;
  url: string;
  /** Absolute link to the service page */
  page: string;
  files: { name: string; content: string }[];
}

export interface StackFile {
  path: string;
  content: string;
  mode?: number;
}

/** 32 random bytes as hex */
export function randomSecret() {
  const b = new Uint8Array(32);
  crypto.getRandomValues(b);
  return Array.from(b, (x) => x.toString(16).padStart(2, '0')).join('');
}

/** Replaces all placeholders with the visitor's values. `__SECRET__` gets a new value per occurrence. */
export function fill(text: string, s: Setup, secret: () => string = randomSecret) {
  const map = placeholders as Record<string, keyof Setup>;
  return text.replace(PH_RE, (m, ph: string, arg?: string) => {
    if (arg !== undefined) return appDataDir(s, arg);
    if (ph === 'SECRET') return secret();
    return map[ph] ? String(s[map[ph]]) : m;
  });
}

/** Folder name inside the ZIP: last part of the root path */
export const rootName = (s: Setup) =>
  (s.root.split('/').filter(Boolean).at(-1) ?? '').replace(/[^\w.-]+/g, '-').replace(/^\.+/, '') || 'homelab';

/** Single-quoted shell word */
const q = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
const fmt = (s: string, vars: Record<string, string | number>) => s.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? ''));

/** Services with the reverse proxies first */
export const proxyFirst = <T extends { isProxy: boolean }>(list: T[]) => [...list.filter((s) => s.isProxy), ...list.filter((s) => !s.isProxy)];

/** Caddyfile made of the global options block of the template plus one block per picked service */
function caddyfile(template: string, snippets: string[]) {
  const global = /^\{[\s\S]*?\n\}\n?/.exec(template.trim() + '\n')?.[0];
  if (!global || !snippets.length) return template;
  return `${global.trimEnd()}\n\n# One block per service (generated by the yourhomelab stack builder)\n${snippets.join('\n\n')}\n`;
}

export function setupScript(list: StackService[], s: Setup, meta: { toolUrl: string }) {
  const L: string[] = [];
  const sorted = proxyFirst(list);
  const proxies = sorted.filter((x) => x.isProxy);
  const others = sorted.filter((x) => !x.isProxy);
  const dir = (id: string) => `${s.root}/${id}`;
  L.push(
    '#!/usr/bin/env bash',
    '# Homelab stack, generated by the yourhomelab stack builder:',
    `# ${meta.toolUrl}`,
    `# Services: ${sorted.map((x) => x.id).join(', ')}`,
    '#',
    '# Run it from inside the unpacked folder:  bash setup.sh',
    `# It needs write access to ${s.root}${s.dataMode === 'central' ? ` and ${s.dataRoot}` : ''} (use sudo if needed) and a running Docker.`,
    'set -euo pipefail',
    '',
    '# Work relative to the folder this script lives in',
    'cd "$(dirname "$0")"',
    '',
    'command -v docker >/dev/null 2>&1 || { echo "Docker is not installed." >&2; exit 1; }',
    '',
    '# Copies a file only if the target does not exist yet.',
    '# Existing files are NEVER overwritten, so running this script again keeps your',
    '# edited compose.yaml and your .env (with its secrets).',
    'copy_new() {',
    '  if [ -e "$2" ]; then',
    '    echo "  kept  $2 (already exists, not overwritten)"',
    '  else',
    '    cp -- "$1" "$2"',
    '    echo "  new   $2"',
    '  fi',
    '}',
    '',
    'echo "==> Creating folders"',
  );
  for (const x of sorted) L.push(`mkdir -p ${q(dir(x.id))}${x.centralData ? ` ${q(`${s.dataRoot}/${x.id}`)}` : ''}`);
  if (sorted.some((x) => x.net)) {
    L.push('', '# Shared network for the reverse proxy (ignored if it already exists)', 'echo "==> Creating the Docker network ' + s.network + '"');
    L.push(`docker network create ${q(s.network)} 2>/dev/null || true`);
  }
  L.push('', 'echo "==> Copying stack files (existing files are kept)"');
  for (const x of sorted) {
    for (const f of ['compose.yaml', '.env', ...x.files.map((f) => f.name)]) L.push(`copy_new ${q(`${x.id}/${f}`)} ${q(`${dir(x.id)}/${f}`)}`);
    L.push(`chmod 600 ${q(`${dir(x.id)}/.env`)}`);
  }
  const up = (x: StackService) => `(cd ${q(dir(x.id))} && docker compose up -d)`;
  if (proxies.length) {
    L.push('', '# The reverse proxy goes first, so the other services can join its network', 'echo "==> Starting the reverse proxy"');
    proxies.forEach((x) => L.push(up(x)));
  }
  if (others.length) {
    L.push('', 'echo "==> Starting the services"');
    others.forEach((x) => L.push(up(x)));
  }
  L.push('', 'echo', 'echo "Done. Check the containers with: docker ps"');
  for (const x of sorted) L.push(`echo ${q(`  ${x.name}: ${x.url}`)}`);
  return L.join('\n') + '\n';
}

export interface StackTexts {
  readmeTitle: string;
  readmeIntro: string;
  readmeSteps: string;
  readmeStep1: string;
  readmeStep2: string;
  readmeStep3: string;
  readmeStep4: string;
  readmeServices: string;
  readmeService: string;
  readmeMore: string;
  proxyCaddy: string;
  proxyNpm: string;
}

export function readme(list: StackService[], s: Setup, tx: StackTexts, meta: { folder: string; date: string; toolUrl: string; hasProxyFile: boolean }) {
  const sorted = proxyFirst(list);
  const steps = [
    fmt(tx.readmeStep1, { folder: meta.folder }),
    tx.readmeStep2,
    fmt(tx.readmeStep3, { root: s.root }),
    ...(meta.hasProxyFile ? [tx.readmeStep4] : []),
  ];
  return [
    `# ${tx.readmeTitle}`,
    '',
    fmt(tx.readmeIntro, { date: meta.date, services: sorted.map((x) => x.name).join(', ') }),
    '',
    `## ${tx.readmeSteps}`,
    '',
    ...steps.map((st, i) => `${i + 1}. ${st}`),
    '',
    `## ${tx.readmeServices}`,
    '',
    ...sorted.map((x) => `- ${fmt(tx.readmeService, { name: x.name, url: x.url, page: x.page })}`),
    '',
    fmt(tx.readmeMore, { url: meta.toolUrl }),
    '',
  ].join('\n');
}

/** All files of the download, paths relative to the ZIP root */
export function buildStack(list: StackService[], s: Setup, tx: StackTexts, meta: { date: string; toolUrl: string; secret?: () => string }): StackFile[] {
  const folder = rootName(s);
  const sorted = proxyFirst(list).map((x) => ({ ...x, url: fill(x.url, s) }));
  const out: StackFile[] = [];
  const snippets = sorted.filter((x) => x.proxy && x.proxyKind === s.proxy).map((x) => ({ name: x.name, text: fill(x.proxy!, s) }));
  for (const x of sorted) {
    out.push({ path: `${folder}/${x.id}/compose.yaml`, content: fill(x.compose, s).trimEnd() + '\n' });
    out.push({ path: `${folder}/${x.id}/.env`, content: fill(x.env, s, meta.secret).trimEnd() + '\n', mode: 0o600 });
    for (const f of x.files) {
      let content = fill(f.content, s);
      if (x.id === 'caddy' && s.proxy === 'caddy' && f.name === 'Caddyfile') content = caddyfile(content, snippets.map((sn) => sn.text));
      out.push({ path: `${folder}/${x.id}/${f.name}`, content });
    }
  }
  const hasProxyFile = snippets.length > 0 && (s.proxy === 'caddy' || s.proxy === 'npm');
  if (hasProxyFile) {
    const intro = s.proxy === 'caddy' ? fmt(tx.proxyCaddy, { file: `${s.root}/caddy/Caddyfile` }) : tx.proxyNpm;
    const body = snippets.map((sn) => `# ${sn.name}\n${sn.text}`).join('\n\n');
    out.unshift({ path: `${folder}/PROXY.txt`, content: `${intro.split('\n').map((l) => `# ${l}`.trimEnd()).join('\n')}\n\n${body}\n` });
  }
  out.unshift(
    { path: `${folder}/README.md`, content: readme(sorted, s, tx, { folder, date: meta.date, toolUrl: meta.toolUrl, hasProxyFile }) },
    { path: `${folder}/setup.sh`, content: setupScript(sorted, s, meta), mode: 0o755 },
  );
  return out;
}
