services:
  authentik:
    image: ghcr.io/goauthentik/server:2025.8
    container_name: authentik
    restart: unless-stopped
    command: server
    environment:
      - TZ=${TZ}
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PG_PASS}
      - AUTHENTIK_REDIS__HOST=redis
    volumes:
      - ./data/media:/media
    depends_on:
      - postgresql
      - redis

  worker:
    image: ghcr.io/goauthentik/server:2025.8
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    environment:
      - AUTHENTIK_SECRET_KEY=${AUTHENTIK_SECRET_KEY}
      - AUTHENTIK_POSTGRESQL__HOST=postgresql
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=${PG_PASS}
      - AUTHENTIK_REDIS__HOST=redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/media:/media

  postgresql:
    image: postgres:16-alpine
    container_name: authentik-postgresql
    restart: unless-stopped
    environment:
      - POSTGRES_USER=authentik
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=authentik
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: authentik-redis
    restart: unless-stopped
