services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      # Used for links in notifications
      - APP_URL=__URL__
    volumes:
      - ./data/data:/beszel_data
