services:
  beszel:
    # Hub and agents should run the same version: update both together
    image: henrygd/beszel:0.20
    container_name: beszel
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      # Used for links in notifications
      - APP_URL=__URL__
    volumes:
      - ./data/data:/beszel_data
